---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: govau/cga-cf-bosh-cli
    tag: latest

inputs:
- name: ci
- name: src

outputs:
- name: build

params:
  DOMAIN:

run:
  path: ci/build.sh
